name: Build , Test and Run Application

env:
  JAVA_VERSION: '17'
  PACKAGE_LOCATION: ./app.zip

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'build.gradle'

  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'build.gradle'

jobs:

  build-and-deploy:
    name: Build & Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ env.JAVA_VERSION }}

      - name: Build with gradle
        run: ./gradlew clean build

      - name: tests with gradle
        run: ./gradlew clean test

      - name: run the application
        run: ./gradlew clean bootRun --args="data/example2.txt"
