name: Build and Deploy

env:
  JAVA_VERSION: '11'
  PACKAGE_LOCATION: ./app.zip

on:
  workflow_dispatch:
  push:
    branches: [Main]
    paths:
      - 'src/**'
      - 'build.gradle'

  pull_request:
    branches: [Main]
    paths:
      - 'src/**'
      - 'build.gradle'

jobs:

  build-and-deploy:
    name: Build & Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ env.JAVA_VERSION }}

      - name: Build with gradle
        run: ./gradlew clean build

      - name: tests with gradle
        run: ./gradlew clean test
